
behaviors = { ...
    'hunch',    'hunch_large_squares',  'blue'; ...
    'bend',     'cast_large_squares',   'red'; ...
    'back',     'back_large_squares',   'cyan'; ...
    'stop',     'stop_large_squares',   'green'; ...
    'run',      'run_large_squares',    'black'; ...
    'roll',     'roll_large_squares',   'yellow'; ...
    'small',    'small_motion_squares', .5 * [1,1,1]};


ethogram = load('../data/ethogramme.mat');

figure();
set(gca, 'FontSize', 18)

ethogram3(ethogram, ...
    'MaxWindow', [90, 140], ...
    'EventOnsetTime', [105, 115, 125], ...
    'EventMaxResponseTime', .3, ...
    'EventOnsetTolerance', .3, ...
    'Behavior', behaviors, ...
    'EventType', { ...
        'hunch', '~hunch', ''; ...
        '~hunch', 'hunch', ''; ...
        }, ...
    %'TransitionsOnlyEvent', true, ...
    'Grouping', {'type', 'onset=3,state'}, ...
    'SortBy', 'end', ...
    'FillGaps', 1);

xlim([100,130])
xlabel('Time from first stimulus onset (s)')
ylabel('Number of animals')

%print('-depsc', 'train_hunch_small_any.eps')
%close

