
behaviors = {'hunch_large_squares', 'blue'; ...
    'cast_large_squares',   'red'; ...
    'back_large_squares',   'cyan'; ...
    'stop_large_squares',   'green'; ...
    'run_large_squares',    'black'; ...
    'roll_large_squares',   'yellow'; ...
    'small_motion_squares', .5 * [1,1,1]};

wd = pwd();
cd('../data')
dirs = ls('-d */');
cd(wd)

for d = 1:size(dirs,1)
    dir_ = strtrim(dirs(d,:));

    figure();
    set(gca, 'FontSize', 18)

    m = ethogram1(['../data/',dir_,'ethogramme.mat'], ...
        'Behavior', behaviors, ...
        'StimulusOnset', 45, ...
        'MaxTimeFromOnset', 10, ...
        'OnsetTolerance', [.2,.5], ...
        'FillGaps', 1, ...
        'Level', 3, ...
        %'NoResponse', 'hide', ...
        %'Exclude', {1, 'small_motion_squares'; 2, 'small_motion_squares'; 3, 'small_motion_squares'}, ...
        'LineWidth', 3);

    xlabel('Time from stimulus onset (s)')
    ylabel('Number of animals')

    print([dir_(1:end-1),'.svg'])
    close
end%for d
