
behaviors = {'hunch_large_squares', 'blue'; ...
    'cast_large_squares',   'red'; ...
    'back_large_squares',   'cyan'; ...
    'stop_large_squares',   'green'; ...
    'run_large_squares',    'black'; ...
    'roll_large_squares',   'yellow'; ...
    'small_motion_squares', .5 * [1,1,1]};

figure();
set(gca, 'FontSize', 18)

ethogram = load('../data/ethogramme.mat');

m = ethogram2(ethogram, ...
    [105, 115, 125, 135, 145], ...
    %[105, 115, 125], ...
    'Behavior', behaviors, ...
    'MaxTimeFromOnset', [7,8], ...
    'OnsetTolerance', [.2,.5], ...
    'FillGaps', 1, ...
    'Level', 1, ...
    'NoResponse', 'hide', ...
    %'Exclude', {1, 'small_motion_squares'; 2, 'small_motion_squares'; 3, 'small_motion_squares'}, ...
    'LineWidth', 2);

xlabel('Time from first stimulus onset (s)')
ylabel('Number of animals')

print('stim_train.svg')
close
