
behaviors = {'hunch_large_squares', 'blue'; ...
    'cast_large_squares',   'red'; ...
    'back_large_squares',   'cyan'; ...
    'stop_large_squares',   'green'; ...
    'run_large_squares',    'black'; ...
    'roll_large_squares',   'yellow'; ...
    'small_motion_squares', .5 * [1,1,1]};

figure();
set(gca, 'FontSize', 18)

ethogram = load('../data/ethogramme.mat');

ethogram2(ethogram, ...
    %[105, 115, 125, 135, 145], ...
    [105, 115, 125], ...
    'Behavior', behaviors, ...
    'MaxTimeFromOnset', [7,8], ...
    'OnsetTolerance', [.3,.6], ...
    'FillGaps', 1, ...
    'Level', 1, ...
    %'NoResponse', 'hide', ...
    'Include', 'hunch_large_squares', ...
    'LineWidth', 2);

xlabel('Time from first stimulus onset (s)')
ylabel('Number of animals')

print('-depsc', 'stim_train1.eps')
close


order1 = ethogram2(ethogram, ...
    %[105, 115, 125, 135, 145], ...
    [105, 115, 125], ...
    'Behavior', behaviors, ...
    'MaxTimeFromOnset', [7,8], ...
    'OnsetTolerance', [.3,.6], ...
    'FillGaps', 1, ...
    'Level', 1, ...
    %'NoResponse', 'hide', ...
    %'Include', 'hunch_large_squares', ...
    'Include', {2, 'hunch_large_squares'}, 'Exclude', {1, 'hunch_large_squares'}, ...
    %'Exclude', {1, 'small_motion_squares'; 2, 'small_motion_squares'; 3, 'small_motion_squares'}, ...
    'LineWidth', 2);

order2 = ethogram2(ethogram, ...
    %[105, 115, 125, 135, 145], ...
    [105, 115, 125], ...
    'Behavior', behaviors, ...
    'MaxTimeFromOnset', [7,8], ...
    'OnsetTolerance', [.3,.6], ...
    'FillGaps', 1, ...
    'Level', 1, ...
    %'NoResponse', 'hide', ...
    'Include', {1, 'hunch_large_squares'}, 'Exclude', {2, 'hunch_large_squares'}, ...
    'ymin', numel(order1), ...
    'LineWidth', 2);

xlabel('Time from first stimulus onset (s)')
ylabel('Number of animals')

print('-depsc', 'stim_train2.eps')
close
