
Fig = 5

behaviors = {'hunch_large_squares', 'blue'; ...
    'cast_large_squares',   'red'; ...
    'back_large_squares',   'cyan'; ...
    'stop_large_squares',   'green'; ...
    'run_large_squares',    'black'; ...
    'roll_large_squares',   'yellow'; ...
    'small_motion_squares', .5 * [1,1,1]};

wd = pwd();
cd('../data')
%dirs = ls('-d */');
%dirs = ['11F06/';'27B12/';'30E06/';'65B04/';'85F12/']
%dirs = ['13G10/';'19-12/ ';'36B06/';'45D11/';'61D08/';'66A12/';'68A08/';'68B05/';'73H04/';'77B12/';'iav/  ';'nompC/'];
if Fig == 4
dirs = ['13A08/';'32E04/';'11A07/';'39H05/'; '88C11/';'66A12/'];
elseif Fig == 5
dirs = ['11F06/                   '; ...
        '23D10/                   '; ...
        'T5_plots/ethograms/23A05/'; ...
        '27B12/                   '; ...
        '29D11/                   '; ...
        '30E06/                   '; ...
        '61A01/                   '; ...
        '65B04/                   '; ...
        'T5_plots/ethograms/77H11/'; ...
        '82B06/                   '; ...
        'T5_plots/ethograms/92H01/'];
end%if
%dirs = ls('-d T5_plots/ethograms/*/')
cd(wd)

for d = 1:size(dirs,1)
    dir_ = strtrim(dirs(d,:));

    figure();
    set(gca, 'FontSize', 18)

    m = ethogram1(['../data/',dir_,'ethogramme.mat'], ...
        'Behavior', behaviors, ...
        'StimulusOnset', 45, ...
        'MaxTimeFromOnset', 3, ...
        'OnsetTolerance', [.2,.5], ...
        'FillGaps', 1, ...
        'Level', 2, ...
        %'NoResponse', 'hide', ...
        %'Exclude', {1, 'small_motion_squares'; 2, 'small_motion_squares'; 3, 'small_motion_squares'}, ...
        'LineWidth', 3);

    xlabel('Time from stimulus onset (s)')
    ylabel('Number of animals')

    larva = dir_(1:end-1);
    larva = strsplit(larva, '/'){end};
    %print('-depsc', [larva,'_ethogram.eps'])
    file = [larva,'_ethogram.png'];
    print('-dpng', '-r300', '-F:30', file)
    close
    system(['convert ', file, ' -transparent white ', file]);
end%for d
